name: drandom
description: Alternative pseudorandom random number generator for dart based on a similar implementation in mono/C#
version: 0.0.1
author: Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/financeCoding/DRandom
dependencies:
  unittest: 0.2.7
